import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { motion } from 'framer-motion';
import Navbar from '../../components/Navbar';
export default function Collection6() {
    const [isChinese, setIsChinese] = useState(true);
    return (_jsxs("main", { className: "bg-gradient-to-b from-gray-900 to-gray-800 text-white font-sans min-h-screen", children: [_jsx(Navbar, { isChinese: isChinese, onLanguageToggle: () => setIsChinese(!isChinese) }), _jsx("section", { className: "pt-32 pb-16 px-6 md:px-20", children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 40 }, animate: { opacity: 1, y: 0 }, transition: { duration: 1 }, className: "text-center mb-16", children: [_jsx("h1", { className: "text-4xl md:text-6xl font-bold mb-6", children: isChinese ? '满工錾花蚊灯' : 'Fine-Engraved Tin Mosquito Lamp' }), _jsx("p", { className: "text-xl text-gray-300 max-w-3xl mx-auto", children: isChinese
                                        ? '匠心造形，照明之外的生活智慧'
                                        : 'A Subtle Union of Function and Gracet' })] }), _jsxs("div", { className: "grid md:grid-cols-2 gap-12 items-start", children: [_jsxs(motion.div, { initial: { opacity: 0, x: -50 }, animate: { opacity: 1, x: 0 }, transition: { duration: 1, delay: 0.3 }, className: "space-y-6", children: [_jsx("img", { src: "/images/collection/collection6.jpg", alt: isChinese ? '满工錾花蚊灯' : 'Fine-Engraved Tin Mosquito Lamp', className: "w-full rounded-lg shadow-2xl" }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx("img", { src: "/images/collection/collection6-detail1.jpg", alt: "Modern Design Detail", className: "w-full rounded-lg shadow-lg" }), _jsx("img", { src: "/images/collection/collection6-detail2.jpg", alt: "Contemporary Style", className: "w-full rounded-lg shadow-lg" })] })] }), _jsxs(motion.div, { initial: { opacity: 0, x: 50 }, animate: { opacity: 1, x: 0 }, transition: { duration: 1, delay: 0.5 }, className: "space-y-8", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: isChinese ? '历史背景' : 'Historical Background' }), _jsx("p", { className: "text-gray-300 leading-relaxed", children: isChinese
                                                        ? '蚊灯流行于清代，是古人夏夜常用的防蚊照明器具。此件满工錾花蚊灯约制于清末民初，造型独特，兼具实用与装饰价值。它体现了古代民居生活中“以器成理”的生活智慧：灯不止为照明之具，更寄寓对安宁与洁净生活的追求。'
                                                        : 'Mosquito lamps were widely used during the late Qing and early Republican periods as both lighting devices and insect repellents. This finely engraved tin lamp, with its unique form and refined decoration, reflects the practical ingenuity and aesthetic sensibility of traditional Chinese domestic life. Beyond illumination, it embodies the pursuit of comfort, cleanliness, and quiet elegance in everyday living.' })] }), _jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: isChinese ? '工艺技艺' : 'Craftsmanship' }), _jsx("p", { className: "text-gray-300 leading-relaxed", children: isChinese
                                                        ? '蚊灯以精炼锡铸成，通体满工錾花。工匠以细錾描绘花卉与卷草纹饰，线条柔密、层次分明，打磨后银光内敛。灯体呈葫芦形，上下以圈足与灯口呼应，侧设喇叭口状通气窗，背后置提柄。灯内燃点后，气流自小窗涌出，蚊虫被吸入灯内并被烟气熏灭，既实用又美观。'
                                                        : 'Cast in pure tin and fully decorated with fine chiseled patterns, the lamp’s surface features dense floral and scroll motifs executed with delicate hammering and engraving. The polished finish lends a soft silvery sheen. The vessel takes the shape of a gourd, with a flaring trumpet-like side opening for air circulation and a handle on the reverse. When lit, warm air draws mosquitoes into the lamp through the small vent, where the flame and smoke eliminate them—a functional yet aesthetically refined design.' })] }), _jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: isChinese ? '造型特点' : 'Design Features' }), _jsx("p", { className: "text-gray-300 leading-relaxed", children: isChinese
                                                        ? '器身高约10.5厘米，比例匀称。灯体圆润饱满，喇叭口与提柄平衡成趣，整体构思巧妙。錾刻花纹繁复细致，层层叠映，呈现出晚清锡器工艺的高峰水准。其喇叭形开口兼具功能与形式之美，使整器在简约中透出雅致。'
                                                        : 'Standing 10.5 centimeters tall, the lamp’s body is rounded and well balanced, combining practicality with sculptural harmony. The flared opening and rear handle create a dynamic visual rhythm, while the intricate engraving covers the entire surface in a rich, rhythmic pattern. The lamp’s structure integrates geometry and utility, achieving both technical precision and understated beauty.' })] }), _jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: isChinese ? '艺术价值' : 'Artistic Value' }), _jsx("p", { className: "text-gray-300 leading-relaxed", children: isChinese
                                                        ? '满工錾花蚊灯不仅是一件生活器物，更是匠人审美与智慧的结晶。它体现了中国古代器物中“以用见美”的设计哲学，也折射出传统工艺中对生活细节的体贴关怀。作为锡制照明器具的重要代表，这件蚊灯见证了民间生活与金属工艺结合的精妙成就。'
                                                        : 'This mosquito lamp is more than a household utensil—it is a manifestation of craftsmanship and cultural intelligence. It embodies the philosophy of “beauty through utility” central to traditional Chinese design, merging practical purpose with refined artistry. As a representative example of late Qing tin lighting ware, it stands as a testament to the fusion of everyday life and exquisite metalworking craftsmanship.' })] })] })] })] }) }), _jsx("footer", { className: "bg-black text-center py-8 text-gray-400 text-sm", children: _jsx("p", { children: isChinese
                        ? '© 2025 中国锡器博物馆 | 传承匠心，用心设计'
                        : '© 2025 China Pewter Museum | Designed with Heritage and Heart' }) })] }));
}
